### ISSUE TITLE
How about using @JSImport instead of @JSGlobal

### ISSUE THREAD

**Issue by weihsiu** [dcascaval/scala-threejs-facades#1]
First of all, thanks for this wonderful library.  I used ScalablyTyped in the past to wrap three.js and, even though it worked, was a package naming hell.  Your facades are orthogonal and user-friendly.  However, when I tried to use some other three-dependent libraries, I ran into a problem.

Since this facade assumes THREE to be globally available, it requires three.js to be included as a script in the HTML file.  This works fine if all I need is three.  But when I need to include libraries that depend on three, I also need to include the libraries plus all their dependencies as well. I did get it working by using scalajs-bundler and custom webpack.config.js but it was a pain.

So what if instead of using @JSGlobal, we switch to @JSImport and use scalajs-bundler from the get-go.  That way, when we need to add dependencies, we just add them in npmDevDependencies and webpack will take care of including the dependencies for us.

**Comment by dcascaval** [comment]
You're absolutely right, we should use `@JSImport` rather than assuming everything is globally available -- this was largely a hack to get it all to fit together. I'm going to look at doing that over the next week or so. It will require the script that generates them to be cleaned up, as the current setup hard-codes the assumption on global scope instead of properly resolving modules and namespaces. 

Do you happen to have an example repo of the setup you would want to work (but doesn't currently)? Would be great to have a test case to work against.

**Comment by weihsiu** [comment]
here you go and thanks a lot for the help!  hopefully, parse-types will become a useful tool as well.
https://github.com/weihsiu/scala-threejs-facades-examples

**Comment by dcascaval** [comment]
sorry this took so long! I just pushed a change which got it working with webpack, shot a PR to your example repo demoing its use. I'm also working on publishing via sonatype instead of github packages, which should remove the need to be rerunning `sbt publishLocal`. 

let me know if there are any other changes you'd like to see! my usage of `THREE` doesn't hit all that much of the library, so it would be fantastic to have a second opinion or a heads up on any ergonomics issues you encounter :)

**Comment by weihsiu** [comment]
thanks for the hard work.  i am also having a cursory look at three now but should dive deeper into it since a better scala binding is made available ;)
